Set SB_IS_MODULAR=1 for any modular shared library
youtube/cobalt pull request #1169
Opened 2023-08-07 09:28 UTC by niranjanyardi

b/246854012

SB_IS_MODULAR needs to be set for modularly built shared libraries for starboard and cobalt toolchains, so that the symbol visibility controlled by starboard/export.h is set correctly.

2023-08-07 13:42 UTC, andrewsavage1 requested changes

2023-08-07 16:55 UTC, niranjanyardi commented on starboard/build/config/BUILDCONFIG.gn
> +  if (build_with_separate_cobalt_toolchain) {
Good point about executables.
How about starboard/build/config/BUILD.gn ? in the base config ?

2023-08-07 17:03 UTC, andrewsavage1 commented on starboard/build/config/BUILDCONFIG.gn
> +  if (build_with_separate_cobalt_toolchain) {
What was wrong with the previous location for it? It's probably okay in the base config, but it then gets included when we build with the native toolchain as well

2023-08-07 17:07 UTC, niranjanyardi commented on starboard/build/config/BUILDCONFIG.gn
> +  if (build_with_separate_cobalt_toolchain) {
Ahh my bad, i thought you wanted to put this in a configuration.gni file.

Ok so ill make a config with the define and then import it for shared libraries and executables in the same file (BUILDCONFIG.gn) .. sg ?

2023-08-07 17:32 UTC, andrewsavage1 commented on starboard/build/config/BUILDCONFIG.gn
> +  if (build_with_separate_cobalt_toolchain) {
No, I'm asking what is wrong with the existing location for it in the "starboard" config?

2023-08-07 21:33 UTC, niranjanyardi commented on starboard/build/config/BUILDCONFIG.gn
> +  if (build_with_separate_cobalt_toolchain) {
This will be set correctly in this PR : https://github.com/youtube/cobalt/pull/1181

2023-08-08 00:30 UTC, niranjanyardi commented on starboard/build/config/BUILDCONFIG.gn
> +  if (build_with_separate_cobalt_toolchain) {
Im not sure when the other PR will land , im restarting this

2023-08-11 07:54 UTC, closed without merging

2023-09-12 21:54 UTC, niranjanyardi commented
Moved to https://github.com/youtube/cobalt/pull/1207/files