Docker Compose V2 and related build fixes
youtube/cobalt pull request #1335
Opened 2023-08-21 18:33 UTC by gramound

Misc build fixes discussed in b/245490832

1. Replacing multiple YAML '<<:' keys with array
2. Replacing 'python' with 'python3'
3. Removing duplicate 'image:' key in xvfb (low confidence, I don't have access to test it)
4. Replacing 'docker-compose' commands with 'docker compose' (with space)

2023-08-21 20:03 UTC, andrewsavage1 requested changes
I'm unsure about the yaml merge key changes, will leave Oscar or Kaido to review that

2023-08-21 20:03 UTC, andrewsavage1 commented on docker-compose-windows-internal.yml
> -# Copyright 2022 The Cobalt Authors. All Rights Reserved.
The copyright year represents when the file was created, we don't want to change it

2023-08-21 20:26 UTC, gramound commented
Ah yes, sorry about the copyright dates. The `check-copyright-year` hook was asking me to change dates and add copyright headers to ~300 files. I later realized it was because my changes were on top of the googlesource.com main branch (no common history with github, so it must have thought I was adding new files). I'll undo those date changes in my next submission.

2023-08-21 21:44 UTC, oxve approved these changes

2023-08-22 17:33 UTC, andrewsavage1 approved these changes

2023-08-24 19:32 UTC, merged

2023-08-24 19:33 UTC, kaidokert commented
Thank you very much for your contributions ! Really helpful. We'll ensure everything is stable and working and will consider for 24lts as well.