Restore squash commit 71f150f3
youtube/cobalt pull request #1395
Opened 2023-08-24 20:00 UTC by dahlstrom-g

It seems to have been rewritten incorrectly as commit 7905a7ec
(even though the message of commit 99dd62fb references 71f150f3).
No files are changed relative to Cobalt's main branch.

2023-08-24 20:35 UTC, briantting approved these changes

2023-08-25 04:45 UTC, kaidokert requested changes
Please always put the package / directory name in the PR title, so commit logs make it obvious which part was changed.

2023-08-25 04:50 UTC, dahlstrom-g commented
> Please always put the package / directory name in the PR title, so commit logs make it obvious which part was changed.

done

2023-08-25 04:55 UTC, dahlstrom-g commented
> Please always put the package / directory name in the PR title, so commit logs make it obvious which part was changed.

It is obvious in logs regardless:
```
*   15d0263e Merge commit '71f150f3bc4a7c8c1b52f16e23539e4025b8caac' as 'cobalt/updater'
|\  
| * 71f150f3 Squashed 'cobalt/updater/' content from commit 63b1176462a
```

2023-08-25 05:00 UTC, merged