Add telemetry for `SourceBuffer.appendBuffer`
youtube/cobalt pull request #2586
Opened 2024-03-13 18:14 UTC by at-ninja

Modifies the SourceBufferMetrics class to not be completely stubbed out in gold builds, and use it to send UMA histograms for the time spent in `SourceBuffer::PrepareAppend` and
`SourceBufferAppendAlgorithm::Process`.

Added basic unit tests for the `SourceBufferMetrics` class, to assert that the new code reports telemetry against the correct histograms.

b/329439818

Change-Id: I7921434b02c689b645ab2a60464eee166d829135

2024-03-13 20:15 UTC, sideb0ard requested changes
Looks great! Added some minor comments.

2024-03-13 20:15 UTC, sideb0ard commented on cobalt/dom/source_buffer_metrics.h
>    void StartTracking();
lets add the SourceBufferMetricsAction enum to StartTracking too, to be consistent with EndTracking. Lets add a DCHECK or similar to ensure the EndTracking matches the correct StartTracking

2024-03-13 22:51 UTC, joeltine commented on tools/metrics/histograms/metadata/cobalt/histograms.xml
> +<variants name="SourceBufferMetricsAction">
Correct. Sorry about that. Just haven't implemented this yet.

2024-03-13 22:51 UTC, joeltine commented on cobalt/dom/source_buffer_metrics.cc
> +          50);
Were you able to test these histograms locally? How was your bucket distribution? I wonder about your min/max ranges here and your bucket size (50). 1 microsecond to 1 second is a delta of 999,999. This is a very wide range... is 50 buckets too coarse? Can you tighten your interval here reasonably and also perhaps up the buckets to 100?

2024-03-14 21:21 UTC, sideb0ard approved these changes
thanks for the changes, lgtm, pending Joel's approval of histogram buckets.

2024-03-14 21:37 UTC, joeltine commented on tools/metrics/histograms/metadata/cobalt/histograms.xml
> +    units="ms" expires_after="never">
aren't your units microseconds?

2024-03-14 21:37 UTC, joeltine commented on cobalt/dom/source_buffer_metrics.cc
> +          50);
Looks good.

2024-03-14 21:55 UTC, at-ninja commented on tools/metrics/histograms/metadata/cobalt/histograms.xml
> +    units="ms" expires_after="never">
Fixed.

2024-03-14 21:56 UTC, joeltine approved these changes

2024-03-14 23:11 UTC, merged