Deprecate SbThreadLocalKey
youtube/cobalt pull request #3096
Opened 2024-04-26 14:29 UTC by y4vor

b/302335657

Test-On-Device: true
Change-Id: If4ea60a099fcfcf30632d18d7b76ed8bc53e5724

2024-04-29 21:03 UTC, y4vor commented on starboard/thread.h
> -#endif
done

2024-04-30 15:56 UTC, andrewsavage1 requested changes

2024-04-30 15:56 UTC, andrewsavage1 commented on base/observer_list_threadsafe.cc
> +  EnsureThreadLocalKeyInited();
I don't have an issue with the change here, but I think it should be separate from this PR as it is changing behavior (even though it's probably for the better), while this PR should just be a refactor. Also, if we're going to change our pattern to call the Ensure* function in the key getters, then we should remove the calls to Ensure* where it currently is, at the callsite of the key getters.

2024-04-30 16:05 UTC, andrewsavage1 commented on starboard/shared/win32/thread_private.cc
> +    return NULL;
nit: can we use nullptr here instead?

2024-04-30 17:00 UTC, andrewsavage1 approved these changes

2024-05-02 22:17 UTC, merged