Add extended IFA support to H5vccSystem
youtube/cobalt pull request #3292
Opened 2024-05-18 03:37 UTC by gbournou

b/334143349

2024-05-18 04:34 UTC, jellefoks requested changes

2024-05-18 04:34 UTC, jellefoks commented on cobalt/h5vcc/h5vcc_system.cc
>  #else
Should this here become an #endif so that the extension can also work for >=14?

2024-05-18 04:34 UTC, jellefoks commented on cobalt/h5vcc/h5vcc_system.cc
>  #else
Also, here #endif?

2024-05-18 04:34 UTC, jellefoks commented on cobalt/h5vcc/h5vcc_system.cc
> +    promise_reference->value().Reject();
I'm not sure if this will work as expected, because this reference object will now get destroyed at the end of this method, right before the promise is handed over to JS, and before JS can record a reference to the wrapped promise, so the wrappable promise may get destroyed before it gets accessed from JS, resulting in an occasional use after free crash here (I say may because it may only happen if you're lucky enough for GC to run right at that opportune moment)

It's safer to post a task that binds the promise reference as a parameter so that it remains alive until the task runs, so that there is time for the JS wrapper to grab a reference to the wrappable. That task can be a method/function or lambda that calls resolve on the reference. I think you should be able to find examples where we already use that approach.

2024-05-18 05:03 UTC, jellefoks approved these changes

2024-05-18 14:13 UTC, y4vor approved these changes

2024-05-18 15:44 UTC, merged

2024-05-20 16:10 UTC, kaidokert commented on starboard/extension/ifa.h
> +  //   * UNKNOWN - if the system isn't able to determine a status
Late comment after submission but - could we perhaps add "NOT_SUPPORTED" value here, and then remove the `COBALT_ENABLE_EXTENDED_IFA` compile-time config entirely, making the API always available ?