linux crashpad 64bit native build fail
youtube/cobalt pull request #3426
Opened 2024-06-03 07:50 UTC by Hyobo

https://partnerissuetracker.corp.google.com/u/0/issues/310759560

Problem:
crashpad use native target build which use boringssl. and 64bit build fail.

Solution:
Add 64bit build case

Verify:
Local test

2024-06-13 13:18 UTC, hlwarriner commented
Thanks for contributing this change - it looks good.

Can you please just update the subject line of the commit message to use the imperative? https://cbea.ms/git-commit/#imperative

For example, "Enable native build of boringssl for arm64"

2024-06-14 13:56 UTC, hlwarriner requested changes
Please see my other comment about the commit message. Otherwise, the change looks good!

2024-07-08 17:46 UTC, kaidokert commented
> Please see my other comment about the commit message. Otherwise, the change looks good!

I've updated - please have a quick look and let's merge if looks okay.

2024-07-08 17:56 UTC, hlwarriner approved these changes

2024-07-09 07:19 UTC, merged