Bump Starboard version in site gen script
youtube/cobalt pull request #3486
Opened 2024-06-07 00:22 UTC by oxve

Bonus: handle title node type

Sometimes doxygen decides that headings inside of a module overview is a
'title' instead of a 'heading'. By handling this node those headings
will now correctly have a markdown heading applied.

b/293645066

2024-06-08 03:34 UTC, kaidokert commented on cobalt/site/docs/reference/starboard/configuration-public.md
> +| **`SB_HAS_QUIRK_SUPPORT_INT16_AUDIO_SAMPLES`**<br><br>The implementation is allowed to support kSbMediaAudioSampleTypeInt16 only when this macro is defined.<br><br>By default, this property is unde
This is removed in SB16 - how did it get back in ? missing cherry-pick ?

2024-06-08 03:39 UTC, kaidokert commented on cobalt/site/docs/reference/starboard/modules/14/event.md
> +SbEventId SbEventSchedule(SbEventCallback callback, void *context, int64_t delay)
I'm worried about those here. Technically Starboard 14 shouldn't be changing , and none of the functions should either. @gbournou can you have a look - should we have #ifdef-gated it ?

E.g. for SB16 use definition with int64, for previous versions SbTime ?

2024-06-08 03:40 UTC, kaidokert commented on cobalt/site/docs/reference/starboard/modules/14/media.md
> +void SbMediaSetAudioWriteDuration(int64_t duration)
Same as above - SbTime changes should have been #ifdeffed for Starboard 16 only.

2024-06-08 03:42 UTC, kaidokert commented on cobalt/site/docs/reference/starboard/modules/14/memory.md
> +TODO: Remove the definition once the memory_mapped_file.h extension is
This todo in the docs looks out of place. Maybe we restore old comment and move TODO up so that Doxygen doesn't pick it up ?

2024-06-08 03:43 UTC, kaidokert commented on cobalt/site/docs/reference/starboard/modules/14/player.md
> +*   `int64_t current_media_timestamp`
SbTime->int64 changes. Unsure if those should stay here or not

2024-06-08 03:45 UTC, kaidokert requested changes
Please double-check with @gbournou if the SbTime -> int64 changes in pre-16 Starboard are as expected. We may need a few more #ifdefs around those

2024-06-08 03:46 UTC, kaidokert commented
I'd also maybe split this PR to a few eaiser chunks - one that just deletes SB13, nothing to review there, should be quick to land.

2024-06-11 00:09 UTC, oxve commented
> I'd also maybe split this PR to a few eaiser chunks - one that just deletes SB13, nothing to review there, should be quick to land.

Doing this is easier said than done unfortunately. I'd need to go back to the last docsite ref and regenerate. It looks like I've made some changes to the docker setup that isn't there so the effort to split up is probably not worth it.

As discussed offline I think the solution here is to set up a new workflow that generates these PRs automatically in continuous fashion.

2024-06-11 00:17 UTC, kaidokert approved these changes
I'm okay with getting it in as is then. We can tweak and incrementally correct things once they are staged. 

Still not fully sure if the SbTime->int64 in older versions is really fully okay - @y4vor should voice his opinion.

2024-06-11 02:00 UTC, merged