Debug windows dirent error
youtube/cobalt pull request #3840
Opened 2024-07-16 17:56 UTC by madhurajayaraman

2024-07-19 21:01 UTC, madhurajayaraman commented on base/files/file_enumerator_starboard.cc
> +    error_ = File::Error::FILE_ERROR_FAILED;
Just used FAILED as a catch all, can swap it.

2024-07-20 02:00 UTC, dahlstrom-g requested changes

2024-07-20 02:00 UTC, dahlstrom-g commented on base/files/file_enumerator_unittest.cc
The modification in this file removes code from upstream:
https://chromium.googlesource.com/chromium/src/+/114.0.5735.358/base/files/file_enumerator_unittest.cc#410

2024-07-23 22:49 UTC, madhurajayaraman commented on base/files/file_enumerator_unittest.cc
Should I add an if clause for Windows here? Then we can match the file_enumerator_unittest.cc file to upstream. https://github.com/youtube/cobalt/pull/3840/files#diff-49176cb792325c5e1004e6396092a22f5dd2a9cc86cc6f4917447c3206542cf5R119

2024-07-24 00:28 UTC, kaidokert commented on base/files/file_enumerator_unittest.cc
Yes, i think that would be correct. `BUILDFLAG(IS_WIN)` should not actually be active for our Starboard/windows based builds - that's an upstream Chromium flag and concept. 

So adding it back in _should be_ a no-op for our build configs. It's confusing and don't take my word for it ..

2024-07-24 19:00 UTC, dahlstrom-g approved these changes
no Chromium files modified

2024-07-24 19:00 UTC, merged