[EG] Update the EG updater to allow sideloading
youtube/cobalt pull request #4428
Opened 2024-11-13 23:01 UTC by TyHolc

Add h5vcc API options to skip checking if package signature matches our key and to set a custom URL to check for package updates.

Implement the above features into the updater for non-gold builds only.

Add a stub server for serving packages.

b/325626249

Original change was reviewed here: https://github.com/youtube/cobalt/pull/3938

2024-11-14 23:54 UTC, TyHolc commented
I added an additional compile check for ALLOW_EVERGREEN_SIDELOADING to enable this feature. We should be able to safely submit this now and fully launch it at a later date.

2024-11-15 00:00 UTC, niranjanyardi requested changes

2024-11-15 00:00 UTC, niranjanyardi commented on chrome/updater/configurator.cc
> +#if !defined(COBALT_BUILD_TYPE_GOLD) && ALLOW_EVERGREEN_SIDELOADING
maybe im missing this, is this macro set to false somewhere ? 

#define ALLOW_EVERGREEN_SIDELOADING 0

2024-11-15 00:03 UTC, niranjanyardi commented on chrome/updater/configurator.cc
> +#if !defined(COBALT_BUILD_TYPE_GOLD) && ALLOW_EVERGREEN_SIDELOADING
Apart from this , LGTM 

My understanding is apart from this flag this is asimple cherry-pick of the already reviewed change in trunk

2024-11-15 00:03 UTC, niranjanyardi approved these changes

2024-11-15 00:04 UTC, niranjanyardi reviewed
Apart from this , LGTM

My understanding is apart from this flag this is asimple cherry-pick of the already reviewed change in trunk.

2024-11-15 00:06 UTC, niranjanyardi commented on chrome/updater/configurator.cc
> +#if !defined(COBALT_BUILD_TYPE_GOLD) && ALLOW_EVERGREEN_SIDELOADING
Unresolved comment

2024-11-15 00:07 UTC, niranjanyardi reviewed
apart from open comment lgtm

2024-11-15 00:20 UTC, niranjanyardi approved these changes

2024-11-15 00:20 UTC, niranjanyardi commented
@yuying-y  @lamdbui  do we want this on 24lts and 23lts as well ? are partners updating to those channels ?

2024-11-19 20:38 UTC, TyHolc commented
> @yuying-y @lamdbui do we want this on 24lts and 23lts as well ? are partners updating to those channels ?

I talked with @yuying-y the other day. It seems like we'll only target 25lts and main (though the main changes will likely diverge and need to be re-implemented).

2024-11-19 22:28 UTC, yuying-y approved these changes

2024-12-03 19:02 UTC, merged