Setup default RBE usage, facilitating CI RBE usage.
youtube/cobalt pull request #4604
Opened 2024-12-18 02:39 UTC by briantting

2025-01-09 21:44 UTC, andrewsavage1 commented on DEPS
> +  'rbe_instance': Str('projects/cobalt-actions-prod/instances/default_instance'),
Can't this be specified in the .gclient file instead of us needing to change the DEPS file? Though I don't know if there's a good way to easily do this for all devs

2025-01-09 21:44 UTC, andrewsavage1 commented on buildtools/reclient_cfgs/rewrapper_linux_cc.cfg
We should probably put these files under //cobalt instead

2025-01-09 21:44 UTC, andrewsavage1 commented on build/toolchain/rbe.gni
Maybe there's a way we can set these variables for builds, but it would rely on gn.py—if someone runs `gn gen` locally without arguments do we care if they end up using the chromium reclient server vs ours?

2025-01-09 21:49 UTC, briantting commented on DEPS
> +  'rbe_instance': Str('projects/cobalt-actions-prod/instances/default_instance'),
It should be able to be specified in `.gclient` much like how `download_remoteexec_cfg` is when we do `gclient config --name=src https://github.com/${{ github.repository }} --custom-var=download_remoteexec_cfg=True`, but I wasn't sure we wanted to ever "risk" using `rbe-chrome-untrusted`.

Also secondly, it's a dumb question but how do you pass "/" chars in key=value command line arg. `--custom-var=rbe_instance=projects/cobalt-actions-prod/instances/default_instance' throws errors. I've tried using quotes and escape chars

2025-01-09 21:56 UTC, briantting commented on build/toolchain/rbe.gni
I rather not risk it.

1. they won't be able to because the default files will not exist since we aren't running CIPD to download them / we won't require people to have chromium CIPD access

2. if they did manage it would be slower since the Chromium's instances cache wont be updated with our compile tasks constantly like our instance's cache would be.

2025-01-09 22:02 UTC, briantting commented on buildtools/reclient_cfgs/rewrapper_linux_cc.cfg
will do

2025-01-10 16:10 UTC, andrewsavage1 commented on DEPS
> +  'rbe_instance': Str('projects/cobalt-actions-prod/instances/default_instance'),
Seems like a quirk of gclient, not bash, but both of these worked for me:
```
$ gclient config --name=src https://github.com/youtube/cobalt.git --custom-var='download_remoteexec_cfg="foo/bar"'
$ gclient config --name=src https://github.com/youtube/cobalt.git --custom-var=download_remoteexec_cfg=\"foo/bar\"
```

2025-01-10 16:13 UTC, andrewsavage1 commented on build/toolchain/rbe.gni
Well people will have to use gn.py to build Cobalt (for now), and local devs are almost never building chromium, so it would only be relevant when people both (1) use gn gen with default args and then (2) change the gn gen args to set useremote_exec=true

2025-01-10 20:54 UTC, briantting commented on build/toolchain/rbe.gni
I'm not sure I follow here. Why would we need the rbe cfg files to be variables? We will only have 1 config needed afaik.

Chrome has a rbe cfg file per rbe instance and manages it through CIPD downloads.

2025-01-10 21:03 UTC, andrewsavage1 commented on build/toolchain/rbe.gni
Just to avoid changing upstream code and changing the default way things build—it's a nice-to-have, not a must

2025-01-10 21:21 UTC, briantting commented on DEPS
> +  'rbe_instance': Str('projects/cobalt-actions-prod/instances/default_instance'),
done!

2025-01-10 21:25 UTC, briantting commented on build/toolchain/rbe.gni
Oh, I see what you mean. If someone tries to run without our specific

`gclient config --name=src git@github.com:youtube/cobalt.git --custom-var=download_remoteexec_cfg=True --custom-var='rbe_instance="projects/cobalt-actions-prod/instances/default_instance"'`

then they won't be able to use Chromium's rbe instance since this is a destructive change.

2025-01-10 21:33 UTC, briantting commented on build/toolchain/rbe.gni
I think that's fine. No one should be using / be allowed to use Chromium's RBE instance anyways and even if we somehow preserved the cfg file paths here in `rbe.gni` with some variable it still wouldn't work due to the changes made in `fetch_reclient_cfgs.py` where we basically short circuit any CIPD download logic. No one should have CIPD download permissions either nor should they have Chromium's private docker image download permissions (private docker images are specified in the downloaded cfg files).

In short, we do not support the use of Chromium's RBE instance nor their cfg files nor their CIPD directory nor their private docker images. It's a cascade of permission requirements and no one should need to use their RBE instance over our RBE instance.

If by chance someone forgets our `gclient config` command's custom vars that's not a problem either since no build acceleration will be used at all. It will not fallback to Chromium's and cause a problem.

2025-01-13 21:26 UTC, kaidokert commented on build/toolchain/rbe.gni
> +    rbe_py_cfg_file = "${cobalt_rbe_cfg_dir}/rewrapper_linux_py.cfg"
I'd recommend leaving this part intact, actually.

Create a `cobalt/infra/reclient_cfgs/` and move your config files under identical subdirectories ( python / chromium-browser-clang ) there. Then you don't need this modification here at all.

2025-01-13 21:27 UTC, kaidokert commented on build/toolchain/rbe.gni
> +  cobalt_rbe_cfg_dir = rebase_path("//cobalt/reclient_cfgs", root_build_dir)
I think you should be able to pass in `rbe_cfg_dir` as a variable to GN invocation / args.gn actually, so we dont need another variable here.

2025-01-13 21:28 UTC, kaidokert commented on buildtools/reclient_cfgs/fetch_reclient_cfgs.py
> +           return 0
Are the `return 0` and the extra `return 1` below correct ? Was this bug in upstream code ?

2025-01-13 21:30 UTC, kaidokert commented on buildtools/reclient_cfgs/fetch_reclient_cfgs.py
> +    auth = []
It's not immediately clear and obvious that this modification in upstream code is Cobalt specific, so i would leave at least a comment saying this. It makes next rebase/update slightly easier.

2025-01-13 21:30 UTC, kaidokert reviewed
Took a pass through - please take a look.

Other than the comments, it looks okay

2025-01-13 23:00 UTC, dahlstrom-g requested changes

2025-01-13 23:00 UTC, dahlstrom-g commented on .github/actions/build/action.yaml
It would be better to do unrelated modifications
in a separate commit with a title describing them.
It's a bit worse yet with related and unrelated
diff lines interspersed as they are here.

2025-01-13 23:00 UTC, dahlstrom-g commented on cobalt/build/gn.py
> +    if os.getenv('USE_CC_WRAPPER', default='0') == '1':
Isn't `USE_CC_WRAPPER` itself unused?
Can't we just delete lines 88–90?

2025-01-13 23:13 UTC, briantting commented on cobalt/build/gn.py
> +    if os.getenv('USE_CC_WRAPPER', default='0') == '1':
We can, but keeping these lines here allows someone to use sccache as a fallback just by setting the env var.

2025-01-14 00:00 UTC, briantting commented on build/toolchain/rbe.gni
> +    rbe_py_cfg_file = "${cobalt_rbe_cfg_dir}/rewrapper_linux_py.cfg"
done.

2025-01-14 00:01 UTC, briantting commented on build/toolchain/rbe.gni
> +  cobalt_rbe_cfg_dir = rebase_path("//cobalt/reclient_cfgs", root_build_dir)
done.

2025-01-14 00:16 UTC, briantting commented on buildtools/reclient_cfgs/fetch_reclient_cfgs.py
> +    auth = []
I can actually remove these changes, it was needed to enable auth for CIPD but now we no longer use CIPD.

2025-01-14 00:35 UTC, briantting commented on buildtools/reclient_cfgs/fetch_reclient_cfgs.py
> +           return 0
Added COBALT comment block. Basically we don't want any additional code here to execute as we no longer use CIPD for rewrapper configs and do not plan on supporting CIPD / deal with auth.

2025-01-14 00:50 UTC, briantting commented on .github/actions/build/action.yaml
done.

2025-01-14 02:00 UTC, dahlstrom-g commented on .github/actions/build/action.yaml
> +      - name: Add depot tools to PATH
still unrelated

2025-01-14 02:00 UTC, dahlstrom-g commented on .github/actions/build/action.yaml
> +      - name: gclient sync
still unrelated

2025-01-14 02:00 UTC, dahlstrom-g commented on .github/actions/build/action.yaml
> +      - name: GN gen
still unrelated

2025-01-14 02:00 UTC, dahlstrom-g commented on .github/actions/build/action.yaml
> +      - name: List GN args
still unrelated

2025-01-14 03:00 UTC, dahlstrom-g reviewed
I wrote the comment below in my previous reply
but GitHub silently lost it, so I had to write it again.
This has happened to me repeatedly. 😠
GitHub PRs feel inadequate as a review tool.

2025-01-14 03:00 UTC, dahlstrom-g commented on .github/actions/build/action.yaml
not done?

2025-01-14 03:00 UTC, dahlstrom-g commented on cobalt/build/gn.py
> +    if os.getenv('USE_CC_WRAPPER', default='0') == '1':
I suppose you mean locally, but users don't
have that option before this PR unless perhaps
they set `IS_CI`, which seems unlikely.

Is this easter egg worth the extra complexity?
Will we even know when it stops working?
I don't think so; I say delete it now. ✊

YAGNI and all that.

2025-01-14 13:57 UTC, briantting commented on .github/actions/build/action.yaml
> +      - name: Add depot tools to PATH
It's separated into distinct commits though or did you mean it should be in its own PR?

2025-01-14 21:37 UTC, briantting commented on cobalt/build/gn.py
> +    if os.getenv('USE_CC_WRAPPER', default='0') == '1':
done.

2025-01-14 21:41 UTC, briantting commented on .github/actions/build/action.yaml
ack!

2025-01-15 02:45 UTC, kaidokert approved these changes
My comments are all in, LGTM :+1:

2025-01-15 04:00 UTC, dahlstrom-g submitted a review, later dismissed
LGTM (especially if not squashed)
… are the commits in the right order? 🤷

2025-01-15 06:10 UTC, dahlstrom-g reviewed
As it stands I believe this PR will break Kokoro builds.

nits:
The word “Chrobalt” should probably be
dropped from the PR and commit titles.
The PR and commit titles shouldn't have periods.
https://cbea.ms/git-commit/#end
Each commit title should be imperative.
https://cbea.ms/git-commit/#imperative

2025-01-15 06:10 UTC, dahlstrom-g commented on .github/actions/build/action.yaml
> +        run: gclient config --name=src https://github.com/${{ github.repository }} --custom-var=download_remoteexec_cfg=True --custom-var='rbe_instance="projects/cobalt-actions-prod/instances/default
nit: Options are prescribed _before_ the URL:
`Usage: gclient.py config [options] [url]`

2025-01-16 01:47 UTC, merged