fix PathServiceTest.Get test
youtube/cobalt pull request #506
Opened 2023-05-31 07:41 UTC by victorpasoshnikov

Test was modified according to XBOX limitations

b/219026606

Change-Id: Iea811495b50fd29588ba439a955d9522672adb88

2023-05-31 07:45 UTC, victorpasoshnikov commented
CL 226181

2023-06-05 23:42 UTC, kaidokert requested changes

2023-06-05 23:42 UTC, kaidokert commented on base/path_service_unittest.cc
> +  // Some existing root folders (LocalFolder, LocalCacheFolder, etc.)
When reading the file above, it looks like the general pattern is 
```
#if PORT 
  if (dir_type == DIR_ASSETS)
    check_path_exists = false;
#endif
```
If you add this section above
```
#if defined(STARBOARD)
  if (dir_type == DIR_XYZ) // i don't know what goes here exactly
    check_path_exists = false;
#endif // defined(STARBOARD)
```
Does it fix the issue similarly ? If yes, this approach would be preferable as it doesn't modify common, platform specific upstream Chrome code.

2023-07-12 01:30 UTC, kaidokert commented
@TyHolc ping for a review / comments / thoughts ?

2023-07-12 17:48 UTC, TyHolc commented
> @TyHolc ping for a review / comments / thoughts ?

If we're sure this will be non-disruptive to other platforms by expanding the scope of "does this path exist" to include directories, then I'm fine with this. 

An alternative could be:

```
#if defined(OS_WIN)
  if (dir_type == <LocalFolder> || dir_type == <LocalCacheFolder> || dir_type == <etc>...) {
    if (!DirectoryExists(path)) {
      return false;
    }
    check_path_exists = false;
  }
#endif
```

2023-11-21 01:15 UTC, TyHolc commented
I'm going to leave this test disabled on Xbox for now and close this. Skipping this test with test filters for xbox is preferable to me over having all platforms skip checking their implementation of `Get` for their respective home directories.

2024-01-10 21:54 UTC, closed without merging